controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# JWT Authentication Routes
api_login_check:
    path: /api/login_check
    methods: ['POST']
